name: salas_mobile
description: "Aplicativo salas mobile"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  provider: ^6.1.2
  pretty_dio_logger: ^1.4.0
  shared_preferences: ^2.5.2
  dotenv: ^4.2.0
  device_preview: ^1.2.0
  fluttertoast: ^8.2.12
  empty_widget_pro: ^0.0.5
  font_awesome_flutter: ^10.8.0
  flutter_spinkit: ^5.2.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_icons:
  image_path: "assets/img/logo_provisoria.png"

  android: "launcher_icon"
  ios: true


flutter:


  uses-material-design: true

  assets:
    - assets/img/knuth.png
    - assets/img/logo_provisoria.png


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700